### PR TITLE
ExtractTarXz ported from cloudfoundry/libbuildpack [fixes #21]

### LINKED ISSUE #21: Add ExtractTarXz to match support in cloudfoundry/libbuildpack predecessor
We have `ExtractTarXz ` in https://github.com/cloudfoundry/libbuildpack/blob/1a939ef723cea84764d0d0ad06d31518d8752b96/util.go#L151-L160

I am using `.tar.xz` assets in my v2 pancake-buildpack https://github.com/starkandwayne/pancake-buildpack/blob/4f271718aa281672a4374c862e33fcf82cce1adb/manifest.yml#L18

Could we have .tar.xz support here too please?

### PR DESCRIPTION
**Pull request by drnic**
Provide `ExtractTarXz` for `.tar.xz` dependencies; implementation + helper methods ported from https://github.com/cloudfoundry/libbuildpack/blob/master/util.go#L151-L175

### CODE REVIEW

**Comment by sclevine** [comment]
This library should work on stacks with minimal OS packages, like `ubuntu:bionic` or `scratch` (i.e., no xz). I feel like this PR should use a native go library for xz decompression, like the tgz implementation does: https://github.com/cloudfoundry/libcfbuildpack/blob/master/helper/extract_tar_gz.go

**Comment by drnic** [comment]
I'll switch to https://github.com/xi2/xz (thanks for finding it @sclevine)

**Comment by drnic** [comment]
@sclevine ok, I've replaced the implementation with native golang

**Comment by drnic** [comment]
Thanks @nebnale!

**Pull request closed without merging**
